server:
  port: 8081
content: http://localhost:${server.port}

mybatis:
  type-aliases-package: com.css.nsfw.dp.domain
  mapper-locations: classpath:mapper/*.xml

## local 数据源配置
local:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: wmhuang
  password: wmhuang
  driverClassName: oracle.jdbc.driver.OracleDriver

## arm 数据源配置
arm:
 datasource:
  url: jdbc:oracle:thin:@78.12.73.134:1521:inspur
  username: arm_jhj
  password: arm_jhj
  driverClassName: oracle.jdbc.driver.OracleDriver
  
## wt 数据源配置
wt:
 datasource:
  url: jdbc:oracle:thin:@78.12.73.54:1521/wsbsdb
  username: DB_USER
  password: SHWSBSDB_USER
  driverClassName: oracle.jdbc.driver.OracleDriver

## nfpt 数据源配置
nfpt:
 datasource:
  url: jdbc:oracle:thin:@78.12.73.44:1521/nfptdb
  username: DB_NFGL
  password: NFPTDB_NFGL
  driverClassName: oracle.jdbc.driver.OracleDriver

spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

main:
 station:
  code: 13100000000
default:
 timeSpan: D
 
 
logging:
 level:
  com:
   css:
    nsfw:
     dp:
      dao:
       nfpt: debug